//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden üretildiğinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_musaoglu
{


    public partial class frm_EmployeeDataEntry
    {

        /// <summary>
        /// form1 denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox TextBox9;
        protected global::System.Web.UI.WebControls.TextBox TextBox10;
        protected global::System.Web.UI.WebControls.TextBox TextBox12;
        protected global::System.Web.UI.WebControls.TextBox TextBox15;
        protected global::System.Web.UI.WebControls.TextBox TextBox16;
        protected global::System.Web.UI.WebControls.TextBox TextBox17;
        protected global::System.Web.UI.WebControls.TextBox TextBox18;
        protected global::System.Web.UI.WebControls.TextBox TextBox19;
        protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList2;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList3;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList4;
        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.CheckBox CheckBox;
        protected global::System.Web.UI.WebControls.Button Button1;
        protected global::System.Web.UI.WebControls.Button Button2;




        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource2;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource3;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource4;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource5;

    }
}
